default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 5432
  user: postgres
  password: hogehoge

development:
  <<: *default
  database: ec_api_demo_development

test:
  <<: *default
  database: ec_api_demo_test

production:
  <<: *default
  database: ec_api_demo_production
  password: <%= ENV["EC_API_DEMO_DATABASE_PASSWORD"] %>
  host: pgpool
