name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  container-job:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ruby:3.2.1

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: hogehoge
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bundle

      - name: createdb
        run: bundle exec rails db:create

      - name: DB migration
        run: bundle exec rails db:migrate

      - name: run rspec
        run: bundle exec rspec
